export const CATEGORY_OPTIONS = [
  "Presidential",
  "Governorship",
  "Senatorial",
  "Parliamentary",
  "Women Representative",
];

export const regionCountyMap: Record<string, string[]> = {
  Coast: ["Mombasa", "Kwale", "Kilifi", "Tana River", "Lamu", "Taita Taveta"],
  Nairobi: ["Nairobi"],
  Central: ["Nyandarua", "Nyeri", "Kirinyaga", "Murang’a", "Kiambu"],
  Eastern: [
    "Embu",
    "Kitui",
    "Machakos",
    "Makueni",
    "Isiolo",
    "Meru",
    "Tharaka Nithi",
  ],
  North_Eastern: ["Garissa", "Wajir", "Mandera"],
  Rift_Valley: [
    "Turkana",
    "West Pokot",
    "Samburu",
    "Trans Nzoia",
    "Uasin Gishu",
    "Elgeyo Marakwet",
    "Nandi",
    "Baringo",
    "Laikipia",
    "Nakuru",
    "Narok",
    "Kajiado",
    "Kericho",
    "Bomet"
  ],
  Western: ["Kakamega", "Vihiga", "Bungoma", "Busia"],
  Nyanza: ["Siaya", "Kisumu", "Homa Bay", "Migori", "Kisii", "Nyamira"],
};
export const countyConstituencyMap: Record<string, string[]> = {
  Mombasa: ['Changamwe', 'Jomvu', 'Kisauni', 'Nyali', 'Likoni', 'Mvita'],
  Kwale: ['Msambweni', 'Lunga Lunga', 'Matuga', 'Kinango'],
  Kilifi: ['Kilifi North', 'Kilifi South', 'Kaloleni', 'Rabai', 'Ganze', 'Malindi', 'Magarini'],
  Tana_River: ['Garsen', 'Galole', 'Bura'],
  Lamu: ['Lamu East', 'Lamu West'],
  Taita_Taveta: ['Taveta', 'Wundanyi', 'Mwatate', 'Voi'],
  Garissa: ['Garissa Township', 'Balambala', 'Lagdera', 'Dadaab', 'Fafi'],
  Wajir: ['Wajir East', 'Tarbaj', 'Wajir West', 'Eldas', 'Wajir South'],
  Mandera: ['Mandera West', 'Mandera North', 'Mandera South', 'Mandera East', 'Lafey'],
  Isiolo: ['Isiolo North', 'Isiolo South'],
  Marsabit: ['North Horr', 'Laisamis', 'Saku', 'Moyale'],
  Meru: ['Tigania East', 'Tigania West', 'Igembe South', 'Igembe Central', 'Igembe North', 'Buuri', 'Imenti North', 'Imenti South', 'Imenti Central'],
  Tharaka_Nithi: ['Chuka/Igambang’ombe', 'Maara', 'Tharaka'],
  Embu: ['Manyatta', 'Mbeere North', 'Runyenjes', 'Mbeere South'],
  Kitui: ['Kitui Central', 'Kitui West', 'Kitui East', 'Kitui Rural', 'Mwingi North', 'Mwingi Central', 'Mwingi West'],
  Machakos: ['Mavoko', 'Yatta', 'Kangundo', 'Masinga', 'Matungulu', 'Kathiani', 'Machakos Town', 'Mwala'],
  Makueni: ['Makueni', 'Kibwezi East', 'Kibwezi West', 'Mbooni', 'Kilome', 'Kaiti'],
  Kiambu: ['Gatundu North', 'Gatundu South', 'Githunguri', 'Juja', 'Kabete', 'Kiambaa', 'Kiambu', 'Kikuyu', 'Lari', 'Limuru', 'Ruiru', 'Thika Town'],
  Nyandarua: ['kinangop', 'Ol Kalou', 'Ndaragwa', 'Kipipiri'],
  Nyeri: ['Tetu', 'Kieni', 'Mathira', 'Othaya', 'Nyeri Town', 'Mukurweini'],
  Kirinyaga: ['Mwea', 'Ndia', 'Gichugu', 'Kirinyaga Central'],
  Muranga: ['Kandara', 'Kangema', 'Mathioya', 'Kiharu', 'Maragua', 'Kigumo'],
  Turkana: ['Loima', 'Turkana North', 'Turkana East', 'Turkana Central', 'Turkana South'],
  West_Pokot: ['Kapenguria', 'Kacheliba', 'Sigor', 'Pokot South'],
  Samburu: ['Samburu East', 'Samburu North', 'Samburu West'],
  Trans_Nzoia: ['Saboti', 'Kwanza', 'Endebess', 'Kiminini'],
  Uasin_Gishu: ['Kapseret', 'Moiben', 'Turbo', 'Soy', 'Kesses', 'Ainabkoi'],
  Elgeyo_Marakwet: ['Keiyo North', 'Keiyo South', 'Marakwet East', 'Marakwet West'],
  Nandi: ['Emgwen', 'Aldai', 'Mosop', 'Chesumei', 'Tinderet', 'Nandi Hills'],
  Baringo: ['Mogotio', 'Baringo North', 'Baringo Central', 'Baringo South', 'Eldama Ravine'],
  Laikipia: ['Laikipia East', 'Laikipia West', 'Laikipia North'],
  Nakuru: ['Nakuru Town East', 'Nakuru Town West', 'Subukia', 'Njoro', 'Gilgil', 'Molo', 'Rongai', 'Naivasha', 'Kuresoi South', 'Kuresoi North', 'Bahati'],
  Narok: ['Narok North', 'Narok South', 'Emurua Dikirr', 'Kilgoris', 'Narok East'],
  Kajiado: ['Kajiado East', 'Kajiado North', 'Kajiado West', 'Kajiado Central', 'Kajiado South'],
  Kericho: ['Ainamoi', 'Bureti', 'Belgut', 'Sigowet/Soin', 'kipkelion West', 'Kipkelion East'],
  Bomet: ['sotik', 'Bomet East', 'Bomet Central', 'Konoin', 'Chepalungu'],
  Kakamega: ['Mumias East', 'Mumias West', 'Butere', 'Lugari', 'Matungu', 'Khwisero', 'Shinyalu', 'Ikolomani', 'Malava', 'likuyani', 'Lurambi'],
  Vihiga: ['Vihiga', 'Hamisi', 'Sabatia', 'Luanda', 'Emuhaya'],
  Bungoma: ['Mt. Elgon', 'Sirisia', 'Bumula', 'Webuye West', 'Webuye East', 'Kimilili', 'Kanduyi', 'Tongaren', 'kabuchia'],
  Busia: ['Teso North', 'Teso South', 'Nambale', 'Matayos', 'Butula', 'Funyula', "Budalang'i"],
  Siaya: ['Ugenya', 'Rarieda', 'Gem', 'Uguja', 'Bondo', 'Alego Usonga'],
  Kisumu: ['Kisumu East', 'Kisumu West', 'Kisumu Central', 'Seme', 'Muhoroni', 'Nyakach'],
  Homa_Bay: ['Kasipul', 'Karachuonyo', 'Homa Bay Town', 'Suba South', 'Rangwe', 'Ndhiwa', 'Kabondo Kasipul'],
  Migori: ['Rongo', 'Awendo', 'Uriri', 'Nyatike', 'Suna East', 'Suna West', 'Kuria West', 'Kuria East'],
  Kisii: ['Bonchari', 'Bobasi', 'Bomachoge Borabu', 'Bomachoge Chache', 'Nyaribari Masaba', 'Nyaribari Chache', 'South Mugirango', 'Kitutu Chache North', 'Kitutu Chache South'],
  Nyamira: ['Kitutu Masaba', 'West Mugirango', 'North Mugirango', 'Borabu'],
  Nairobi: ['Dagoretti North', 'Dagoretti South', 'Langata', 'Kibra', 'Kasarani', 'Roysambu', 'Ruaraka', 'Embakasi Central', 'Embakasi East', 'Embakasi North', 'Embakasi South', 'Embakasi West', 'Kamukunji', 'Makadara', 'Mathare', 'Starehe', 'Westlands']
};
