import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footerpage from "./components/Footer";


export const metadata: Metadata = {
  title: "Politrack Africa",
  description: "Generated by Politrack",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body><Navbar />
        {children}
        <Footerpage />
      </body>
    </html>
  );
}

